
var vtPlayerWorker;

var indices;

window.startAudio = async (audioContext) => {

    const audioConstants = await import("./AudioConstants.js");

    const RingBufferSize = audioConstants.RingBufferSize;

    console.log(crossOriginIsolated);

    const buffer = new SharedArrayBuffer(RingBufferSize * 4 + 3 * 4);

    indices = new Int32Array(buffer, RingBufferSize * 4, 3);
    indices[0] = 0;    // Worker-controlled head
    indices[1] = 0;    // Processor-controlled tail
    indices[2] = 0;    // Posted message count

    await audioContext.audioWorklet.addModule('/js/AudioWorklet.js');

    let node = new AudioWorkletNode(audioContext, 'VTPlayerAudioWorklet');
    node.port.postMessage(buffer);
    node.connect(audioContext.destination);

    vtPlayerWorker = new Worker('/js/VTPlayerWorker.js');
    vtPlayerWorker.postMessage({ buffer: buffer, sampleRate: audioContext.sampleRate });
};

const modFiles =
[
    "MOD/8CHN.MOD",
    "MOD/A King is Born.Mod",
    "MOD/AMAROK.MOD",
    "MOD/AMBIENTP.MOD",
    "MOD/ATOMIC2.MOD",
    "MOD/AUSGEBUR.MOD",
    "MOD/BASSBASE.MOD",
    "MOD/Bomb.Mod",
    "MOD/CESAR.MOD",
    "MOD/CHECKNOB.MOD",
    "MOD/CLOUD.MOD",
    "MOD/CONDOM.MOD",
    "MOD/CR-ORBIT.MOD",
    "MOD/CR-STARL.MOD",
    "MOD/cream_of_the_earth.mod",
    "MOD/CRYSTALS.MOD",
    "MOD/Cyberride.Mod",
    "MOD/DANDLION.MOD",
    "MOD/DANGER.MOD",
    "MOD/DARKANGL.MOD",
    "MOD/DARKDAYS.MOD",
    "MOD/DEMODEMO.MOD",
    "MOD/DEMOMOD1.MOD",
    "MOD/DEMOMOD3.MOD",
    "MOD/DOPE.MOD",
    "MOD/ELYSIUM.MOD",
    "MOD/EUPHONIK.MOD",
    "MOD/FEAREXAM.MOD",
    "MOD/FG93.MOD",
    "MOD/FREESPA.MOD",
    "MOD/FREESTYL.MOD",
    "MOD/GLOBALT.MOD",
    "MOD/GSLINGER.MOD",
    "MOD/hedgehog.mod",
    "MOD/HYPNOSST.MOD",
    "MOD/Imaginery Woman.Mod",
    "MOD/INCONEXI003.mod",
    "MOD/INCONEXI005.mod",
    "MOD/INCONEXI008.mod",
    "MOD/INCONEXI014.mod",
    "MOD/INTOFACE.MOD",
    "MOD/INVTRO.MOD",
    "MOD/ITDARK2.MOD",
    "MOD/Klisje paa Klisje.Mod",
    "MOD/KLISJE.MOD",
    "MOD/Lemon Soda.Mod",
    "MOD/LONGTECH.MOD",
    "MOD/LUNATIC.MOD",
    "MOD/m16a.mod",
    "MOD/MASSHYST.MOD",
    "MOD/Molecule's Revenge.Mod",
    "MOD/MOMETHNG.MOD",
    "MOD/MYDICKIN.MOD",
    "MOD/NOCORNER.MOD",
    "MOD/NOWWHAT3.MOD",
    "MOD/NTOLVIDO.MOD",
    "MOD/Occ-san-geen.Mod",
    "MOD/OCC-SAN.MOD",
    "MOD/ODE2PTK.MOD",
    "MOD/OLDTIMES.MOD",
    "MOD/OPTICNRV.MOD",
    "MOD/Optimum Fuckup.Mod",
    "MOD/overture.mod",
    "MOD/physical_presence.mod",
    "MOD/PRODUCT.MOD",
    "MOD/RC_DROPS.MOD",
    "MOD/RE-CALL.MOD",
    "MOD/REDRAIN.MOD",
    "MOD/ROCK.MOD",
    "MOD/SEEDSOF.MOD",
    "MOD/SHADOW.MOD",
    "MOD/SOFTBRIL.MOD",
    "MOD/SOMEOK5.MOD",
    "MOD/SOMEOK6.MOD",
    "MOD/SOMETHNG.MOD",
    "MOD/SPA.MOD",
    "MOD/Stagebox.Mod",
    "MOD/Stardust Memories.Mod",
    "MOD/THEDECAL.MOD",
    "MOD/THEEND.MOD",
    "MOD/THEJOUR.MOD",
    "MOD/tilbury_fair.mod",
    "MOD/TIME.MOD",
    "MOD/VANGELIS.MOD",
    "MOD/Whisper my Thoughts.Mod",
    "MOD/Wizardry.Mod",
    "S3M/(G)FOOLS.S3M",
    "S3M/2ndr-sk.s3m",
    "S3M/2ND_PM.S3M",
    "S3M/2ND_SKAV.S3M",
    "S3M/3RD.S3M",
    "S3M/64mania.s3m",
    "S3M/A94FINAL.S3M",
    "S3M/AMAGO.S3M",
    "S3M/amazonas.s3m",
    "S3M/ANCIENT.S3M",
    "S3M/ANGELH.S3M",
    "S3M/ARMANI.S3M",
    "S3M/ASY-WILD.S3M",
    "S3M/autonom.s3m",
    "S3M/BABYLON.S3M",
    "S3M/BACKWARD.S3M",
    "S3M/CAPTURED.S3M",
    "S3M/CCITY12.S3M",
    "S3M/CHAOS.S3M",
    "S3M/CHIPSIM.S3M",
    "S3M/CONDOM.S3M",
    "S3M/crystald.s3m",
    "S3M/ctgoblin.s3m",
    "S3M/datajack.s3m",
    "S3M/DEM.S3M",
    "S3M/DEMII95.S3M",
    "S3M/DESPAI.S3M",
    "S3M/DESPAIR.S3M",
    "S3M/DREAM3.S3M",
    "S3M/DROLMIX.S3M",
    "S3M/EDEN.S3M",
    "S3M/ESP.S3M",
    "S3M/ETHVISIO.S3M",
    "S3M/EUPHONIK.S3M",
    "S3M/EXPLORAT.S3M",
    "S3M/EXPRESS.S3M",
    "S3M/FLAME.S3M",
    "S3M/FRIENDS.S3M",
    "S3M/GET2.S3M",
    "S3M/GMOTION.S3M",
    "S3M/GSLINGER.S3M",
    "S3M/HAPPY.S3M",
    "S3M/hereyes.s3m",
    "S3M/hgargoyl.s3m",
    "S3M/HYMNE.S3M",
    "S3M/HYPER.S3M",
    "S3M/ICEFRONT.S3M",
    "S3M/ID.S3M",
    "S3M/IDEA.S3M",
    "S3M/intro93.s3m",
    "S3M/invtro94.s3m",
    "S3M/K.S3M",
    "S3M/K_SPIRAL.S3M",
    "S3M/lavender.s3m",
    "S3M/LIVIN2.S3M",
    "S3M/LOOPS.S3M",
    "S3M/LST_TIME.S3M",
    "S3M/MAELSTRM.S3M",
    "S3M/mangrove.s3m",
    "S3M/MASKINA.S3M",
    "S3M/MEGAMOD3.S3M",
    "S3M/mercrain.s3m",
    "S3M/MIRROR.S3M",
    "S3M/mosquito.s3m",
    "S3M/network.s3m",
    "S3M/nighcats.s3m",
    "S3M/noface.s3m",
    "S3M/NOSREAL2.S3M",
    "S3M/not4kids.s3m",
    "S3M/NOWWHAT3.S3M",
    "S3M/NTOLVIDO.S3M",
    "S3M/ODESPAIR.S3M",
    "S3M/OMNIPHIL.S3M",
    "S3M/OPTICNRV.S3M",
    "S3M/oxg.s3m",
    "S3M/PANIC.S3M",
    "S3M/party92.s3m",
    "S3M/POSVIBRA.S3M",
    "S3M/PUBNME.S3M",
    "S3M/ramagard.s3m",
    "S3M/RC_DROPS.S3M",
    "S3M/REALIZE.S3M",
    "S3M/ROCK.S3M",
    "S3M/ROCKING.S3M",
    "S3M/saint.s3m",
    "S3M/SATELL.S3M",
    "S3M/SEASON.S3M",
    "S3M/SPASM95.S3M",
    "S3M/spltfest.s3m",
    "S3M/SPRING.S3M",
    "S3M/STRSHINE.S3M",
    "S3M/suzysgp.s3m",
    "S3M/SWAVES2.S3M",
    "S3M/symphony.s3m",
    "S3M/TECHTECH.S3M",
    "S3M/TOUGH.S3M",
    "S3M/TURBULEN.S3M",
    "S3M/war.s3m",
    "S3M/WOPLSTC.S3M",
    "XM/ANGEL6.XM",
    "XM/DEADLOCK.XM",
    "XM/DRAGON.XM",
    "XM/ELEKTRON.XM",
    "XM/EMPIRE4.XM",
    "XM/FISHLIME.XM",
    "XM/galway.xm",
    "XM/Goatage.xm",
    "XM/GUILDOFS.XM",
    "XM/INTRO4IT.XM",
    "XM/KLISJE2.XM",
    "XM/MSHADOW4.XM",
    "XM/OBLITIRT.XM",
    "XM/PANIC.XM",
    "XM/PROTECT.XM",
    "XM/REFLECTR.XM",
    "XM/RELAX.XM",
    "XM/REZON3.XM",
    "XM/SDELICB2.XM",
    "XM/SLOWIT.XM",
    "XM/songsect.xm",
    "XM/synth_c_chaos-suprise.xm",
    "XM/templsun.xm",
    "XM/THEVOICE.XM",
    "XM/TODO5.XM"
];

window.startNextAudio = async () => {

    const index = Math.floor(Math.random() * modFiles.length);

    const response = await fetch("/MODs/" + modFiles[index]);
    const buffer   = await response.arrayBuffer();

    vtPlayerWorker.postMessage(buffer);
    const oldCount = Atomics.add(indices, 2, 1);
    //console.log('Count increased to ', oldCount + 1);
};
